#cloud-config
package_upgrade: true
packages:
  - docker.io
  - docker-compose
  - dpdk-kmods-dkms
  - jq
groups:
  - docker
users:
  - default
  - name: ${UserName}
    groups: docker
runcmd:
  - sudo -H -u ${UserName} bash -c 'git clone ${GitRepoUrl} $HOME/${GitRepoName}'
  - make pull -C /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/Docker
  - make build -C /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/Python
  - make dpdk -C /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/DPDK
  - make docker-compose -C /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/Docker
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]