version: "2"

services:
  keng-controller:
    image: ghcr.io/open-traffic-generator/ixia-c-controller:0.0.1-3768
    restart: always
    ports:
      - "8443:8443"
      - "40051:40051"
    depends_on:
      otg-ixhw:
        condition: service_started
    command:
      - "--accept-eula"
      - "--ixia-c-ixhw-server"
      - "otg-ixhw:5001"
  otg-ixhw:
    image: ghcr.io/open-traffic-generator/ixia-c-ixhw-server:0.10.7-8
    restart: always
    ports:
      - "5000:5000"
      - "5001:5001"
    command:
      - "dotnet"
      - "otg-ixhw.dll"
