version: "2"
services:
  controller:
    image: ghcr.io/open-traffic-generator/keng-controller:1.5.1-12
    restart: always
    ports:
      - "8443:8443"
      - "40051:40051"
    depends_on:
      layer23-hw-server:
        condition: service_started
    environment:
      - LICENSE_SERVERS=${LICENSE_SERVERS}
    command:
      - "--accept-eula"
      - "--debug"
      - "--keng-layer23-hw-server"
      - "layer23-hw-server:5001"
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "10"
        mode: "non-blocking"
  layer23-hw-server:
    image: ghcr.io/open-traffic-generator/keng-layer23-hw-server:1.5.1-6
    restart: always
    command:
      - "dotnet"
      - "otg-ixhw.dll"
      - "--trace"
      - "--log-level"
      - "trace"
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "10"
        mode: "non-blocking"
  gnmi-server:
    image: ghcr.io/open-traffic-generator/otg-gnmi-server:1.14.2
  traffic_engine_1:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_2:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_3:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_4:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_5:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_6:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  protocol_engine_1:
    image: ghcr.io/open-traffic-generator/ixia-c-protocol-engine:1.00.0.383
  protocol_engine_2:
    image: ghcr.io/open-traffic-generator/ixia-c-protocol-engine:1.00.0.383
  operator:
    image: ghcr.io/open-traffic-generator/keng-hybrid-operator:0.0.4
