version: "2"

services:
  ixia-c-controller:
    image: ghcr.io/open-traffic-generator/licensed/ixia-c-controller:0.0.1-4167
    restart: always
    depends_on:
      ixia-c-ixhw-server:
        condition: service_started
    command:
      - "--accept-eula"
      - "--debug"
      - "--ixia-c-ixhw-server"
      - "ixia-c-ixhw-server:5001"
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "10"
        mode: "non-blocking"
  ixia-c-ixhw-server:
    image: ghcr.io/open-traffic-generator/ixia-c-ixhw-server:0.11.10-13
    restart: always
    command:
      - "dotnet"
      - "otg-ixhw.dll"
      - "--trace"
      - "--log-level"
      - "trace"
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "10"
        mode: "non-blocking"
  ixia-c-gnmi-server:
    image: ghcr.io/open-traffic-generator/ixia-c-gnmi-server:1.11.16
    restart: always
    depends_on:
      ixia-c-controller:
        condition: service_started
    command:
      - "-http-server"
      - "https://ixia-c-controller:8443"
      - "--debug"
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "10"
        mode: "non-blocking"
