#cloud-config
package_upgrade: true
packages:
  - linux-modules-extra-azure
  - emacs
  - iperf
  - iperf3
  - net-tools
runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - az login --identity
  - Agent1Eth1MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth1PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent1Eth2MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth2PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent1Eth3MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth3PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent1Eth4MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth4PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent1Eth5MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth5PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent1Eth6MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth6PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent1Eth7MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent1Eth7PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth1MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth1PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth2MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth2PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth3MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth3PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth4MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth4PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth5MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth5PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth6MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth6PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - Agent2Eth7MacAddress=$(az network nic list --resource-group "${ResourceGroupName}" --query "[].{Name:name, IP:ipConfigurations[0].privateIPAddress, MAC:macAddress}[?IP=='${Agent2Eth7PrivateIpAddresses[0]}']" --output json | jq .[0].MAC --raw-output | tr '-' ':')
  - sed -i "s/Agent1Eth1MacAddress/$Agent1Eth1MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth2MacAddress/$Agent1Eth2MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth3MacAddress/$Agent1Eth3MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth4MacAddress/$Agent1Eth4MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth5MacAddress/$Agent1Eth5MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth6MacAddress/$Agent1Eth6MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth7MacAddress/$Agent1Eth7MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth1MacAddress/$Agent2Eth1MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth2MacAddress/$Agent2Eth2MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth3MacAddress/$Agent2Eth3MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth4MacAddress/$Agent2Eth4MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth5MacAddress/$Agent2Eth5MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth6MacAddress/$Agent2Eth6MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth7MacAddress/$Agent2Eth7MacAddress/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth1IpAddress/${Agent1Eth1PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth2IpAddress/${Agent1Eth2PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth3IpAddress/${Agent1Eth3PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth4IpAddress/${Agent1Eth4PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth5IpAddress/${Agent1Eth5PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth6IpAddress/${Agent1Eth6PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent1Eth7IpAddress/${Agent1Eth7PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth1IpAddress/${Agent2Eth1PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth2IpAddress/${Agent2Eth2PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth3IpAddress/${Agent2Eth3PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth4IpAddress/${Agent2Eth4PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth5IpAddress/${Agent2Eth5PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth6IpAddress/${Agent2Eth6PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth7IpAddress/${Agent2Eth7PrivateIpAddresses[0]}/g" ${GitRepoConfigPath}/*.json
  - sed -i "s/Agent2Eth0IpAddress/${Agent2Eth0IpAddress}/g" ${GitRepoConfigPath}/settings.json
  - make dpdk -C ${GitRepoDeployPath}/DPDK
  - make docker-compose -C ${GitRepoDeployPath}/Docker
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]