services:
  operator:
    image: ghcr.io/open-traffic-generator/keng-hybrid-operator:0.0.4
    command: --server-bind-address=:35000
    pid: "host"
    user: "root"
    network_mode: "host"
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    cap_add:
      - NET_ADMIN
  controller:
    image: ghcr.io/open-traffic-generator/keng-controller:1.5.1-12
  layer23-hw-server:
    image: ghcr.io/open-traffic-generator/keng-layer23-hw-server:1.5.1-6
  gnmi-server:
    image: ghcr.io/open-traffic-generator/otg-gnmi-server:1.14.2
  traffic_engine_1:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_2:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_3:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_4:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_5:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  traffic_engine_6:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.12
  protocol_engine_1:
    image: ghcr.io/open-traffic-generator/ixia-c-protocol-engine:1.00.0.383
  protocol_engine_2:
    image: ghcr.io/open-traffic-generator/ixia-c-protocol-engine:1.00.0.383
