services:
  controller:
    image: ixiacom/ixia-c-controller:0.0.1-3002
    command: --accept-eula --http-port 443
    network_mode: "host"
    restart: always
  traffic_engine_1:
    image: ixiacom/ixia-c-traffic-engine:1.4.1.29
    network_mode: "host"
    restart: always
    privileged: true
    environment:
    - OPT_LISTEN_PORT=5555
    - ARG_IFACE_LIST=virtual@af_packet,veth0
    - OPT_NO_HUGEPAGES=Yes
  traffic_engine_2:
    image: ixiacom/ixia-c-traffic-engine:1.4.1.29
    network_mode: "host"
    restart: always
    privileged: true
    environment:
    - OPT_LISTEN_PORT=5556
    - ARG_IFACE_LIST=virtual@af_packet,veth1
    - OPT_NO_HUGEPAGES=Yes
