apiVersion: v1
kind: Service
metadata:
  name: service-ate-port-eth2
  namespace: ixia-c
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-5555
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: ate-port-eth2
  sessionAffinity: None
  type: LoadBalancer
