version: '3'
services:
  KENG-License-Server:
    image: ghcr.io/open-traffic-generator/keng-license-server:latest
    container_name: keng-license-server
    restart: always
    ports:
      - "7443:7443"
      - "9443:9443"
    command: --accept-eula

  controller:
    image: ghcr.io/open-traffic-generator/keng-controller:1.1.0-21
    command: --accept-eula --http-port 8443 --license-servers="localhost"
    network_mode: "host"
    restart: always
  TE1-5551:
    image: docker-local-ixvm-lbj.artifactorylbj.it.keysight.com/athena-traffic-engine:1.6.0.163
    command: sleep infinity
    network_mode: "host"
    privileged: true
    volumes:
      - /mnt/huge:/mnt/huge
      - /sys/kernel/mm/hugepages:/sys/kernel/mm/hugepages
      - /sys/bus/pci/drivers:/sys/bus/pci/drivers
      - /sys/devices/system/node:/sys/devices/system/node
      - /dev:/dev
    environment:
      - OPT_LISTEN_PORT=5551
      - ARG_IFACE_LIST=pci@0000:03:00.0
      - ARG_CORE_LIST="0 1 2"
