name: CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'docker-compose/b2b/**.yml'

jobs:
  docker-compose-b2b:
    name: Run docker-compose b2b lab
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./docker-compose/b2b
    steps:
    - uses: actions/checkout@v3
    - name: Run all
      run:  make all
