name: CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'docker-compose/b2b/**'
      - '!docker-compose/b2b/**.md'
      - '!docker-compose/b2b/**.png'
      - 'docker-compose/cpdp-b2b/**'
      - '!docker-compose/cpdp-b2b/**.md'
      - '!docker-compose/cpdp-b2b/**.png'
      - 'clab/rtbh/**'
      - '!clab/rtbh/**.md'
      - '!clab/rtbh/**.png'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docker-compose/b2b/**'
      - '!docker-compose/b2b/**.md'
      - '!docker-compose/b2b/**.png'
      - 'docker-compose/cpdp-b2b/**'
      - '!docker-compose/cpdp-b2b/**.md'
      - '!docker-compose/cpdp-b2b/**.png'
      - 'clab/rtbh/**'
      - '!clab/rtbh/**.md'
      - '!clab/rtbh/**.png'
  workflow_dispatch:

jobs:
  paths-filter:
    name: Filter changes to subfolders
    runs-on: ubuntu-20.04
    outputs:
      docker-compose-b2b: ${{ steps.changes.outputs.docker-compose-b2b }}
      docker-compose-cpdp-b2b: ${{ steps.changes.outputs.docker-compose-cpdp-b2b }}
      clab-rtbh: ${{ steps.changes.outputs.clab-rtbh }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            docker-compose-b2b:
            - 'docker-compose/b2b/**'
            docker-compose-cpdp-b2b:
            - 'docker-compose/cpdp-b2b/**'
            clab-rtbh:
            - 'clab/rtbh/**'
      - name: docker-compose b2b
        if: steps.changes.outputs.docker-compose-b2b == 'true'
        run: echo "Run docker-compose b2b CI"
      - name: docker-compose cpdp-b2b
        if: steps.changes.outputs.docker-compose-cpdp-b2b == 'true'
        run: echo "Run docker-compose cpdp-b2b CI"
      - name: clab rtbh
        if: steps.changes.outputs.clab-rtbh == 'true'
        run: echo "Run Clab RTBH CI"
  docker-compose-b2b:
    name: Run docker-compose b2b CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./docker-compose/b2b
    if: needs.paths-filter.outputs.docker-compose-b2b == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Run all
        run:  make all
  docker-compose-cpdp-b2b:
    name: Run docker-compose cpdp-b2b CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./docker-compose/cpdp-b2b
    if: needs.paths-filter.outputs.docker-compose-cpdp-b2b == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Run all
        run:  make all
  clab-rtbh:
    name: Run Clab RTBH CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./clab/rtbh
    if: needs.paths-filter.outputs.clab-rtbh == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Run all
        run:  make all
