name: CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'docker-compose/b2b/**'
      - '!docker-compose/b2b/**.md'
      - '!docker-compose/b2b/**.png'
      - 'docker-compose/b2b-3pair/**'
      - '!docker-compose/b2b-3pair/**.md'
      - '!docker-compose/b2b-3pair/**.png'
      - 'docker-compose/cpdp-b2b/**'
      - '!docker-compose/cpdp-b2b/**.md'
      - '!docker-compose/cpdp-b2b/**.png'
      - 'docker-compose/cpdp-frr/**'
      - '!docker-compose/cpdp-frr/**.md'
      - '!docker-compose/cpdp-frr/**.png'
      - 'clab/ixp-openbgpd/**'
      - '!clab/ixp-openbgpd/**.md'
      - '!clab/ixp-openbgpd/**.png'
      - 'clab/rtbh/**'
      - '!clab/rtbh/**.md'
      - '!clab/rtbh/**.png'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docker-compose/b2b/**'
      - '!docker-compose/b2b/**.md'
      - '!docker-compose/b2b/**.png'
      - 'docker-compose/b2b-3pair/**'
      - '!docker-compose/b2b-3pair/**.md'
      - '!docker-compose/b2b-3pair/**.png'
      - 'docker-compose/cpdp-b2b/**'
      - '!docker-compose/cpdp-b2b/**.md'
      - '!docker-compose/cpdp-b2b/**.png'
      - 'docker-compose/cpdp-frr/**'
      - '!docker-compose/cpdp-frr/**.md'
      - '!docker-compose/cpdp-frr/**.png'
      - 'clab/ixp-openbgpd/**'
      - '!clab/ixp-openbgpd/**.md'
      - '!clab/ixp-openbgpd/**.png'
      - 'clab/rtbh/**'
      - '!clab/rtbh/**.md'
      - '!clab/rtbh/**.png'
  workflow_dispatch:

jobs:
  paths-filter:
    name: Filter changes to subfolders
    runs-on: ubuntu-20.04
    outputs:
      docker-compose-b2b: ${{ steps.changes.outputs.docker-compose-b2b }}
      docker-compose-b2b-3pair: ${{ steps.changes.outputs.docker-compose-b2b-3pair }}
      docker-compose-cpdp-b2b: ${{ steps.changes.outputs.docker-compose-cpdp-b2b }}
      docker-compose-cpdp-frr: ${{ steps.changes.outputs.docker-compose-cpdp-frr }}
      clab-cpdp-frr: ${{ steps.changes.outputs.clab-cpdp-frr }}
      clab-ixp-openbgpd: ${{ steps.changes.outputs.clab-ixp-openbgpd }}
      clab-rtbh: ${{ steps.changes.outputs.clab-rtbh }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            docker-compose-b2b:
            - 'docker-compose/b2b/**'
            docker-compose-b2b-3pair:
            - 'docker-compose/b2b-3pair/**'
            docker-compose-cpdp-b2b:
            - 'docker-compose/cpdp-b2b/**'
            docker-compose-cpdp-frr:
            - 'docker-compose/cpdp-frr/**'
            clab-cpdp-frr:
            - 'docker-compose/cpdp-frr/**'
            clab-ixp-openbgpd:
            - 'clab/ixp-openbgpd/**'
            clab-rtbh:
            - 'clab/rtbh/**'
      - name: docker-compose b2b
        if: steps.changes.outputs.docker-compose-b2b == 'true'
        run: echo "Run docker-compose b2b CI"
      - name: docker-compose b2b-3pair
        if: steps.changes.outputs.docker-compose-b2b-3pair == 'true'
        run: echo "Run docker-compose b2b-3pair CI"
      - name: docker-compose cpdp-b2b
        if: steps.changes.outputs.docker-compose-cpdp-b2b == 'true'
        run: echo "Run docker-compose cpdp-b2b CI"
      - name: docker-compose cpdp-frr
        if: steps.changes.outputs.docker-compose-cpdp-frr == 'true'
        run: echo "Run docker-compose cpdp-frr CI"
      - name: clab cpdp-frr
        if: steps.changes.outputs.clab-cpdp-frr == 'true'
        run: echo "Run clab cpdp-frr CI"
      - name: clab ixp-openbgpd
        if: steps.changes.outputs.clab-ixp-openbgpd == 'true'
        run: echo "Run Clab ixp-openbgpd CI"
      - name: clab rtbh
        if: steps.changes.outputs.clab-rtbh == 'true'
        run: echo "Run Clab RTBH CI"
  docker-compose-b2b:
    name: Run docker-compose b2b CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./docker-compose/b2b
    if: needs.paths-filter.outputs.docker-compose-b2b == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Run all
        run:  make all
  docker-compose-b2b-3pair:
    name: Run docker-compose b2b-3pair CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./docker-compose/b2b-3pair
    if: needs.paths-filter.outputs.docker-compose-b2b-3pair == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.ENV_GITHUB_USER }}
          password: ${{ secrets.ENV_GITHUB_PAT }}
      - name: Run all
        run:  make all
  docker-compose-cpdp-b2b:
    name: Run docker-compose cpdp-b2b CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./docker-compose/cpdp-b2b
    if: needs.paths-filter.outputs.docker-compose-cpdp-b2b == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.ENV_GITHUB_USER }}
          password: ${{ secrets.ENV_GITHUB_PAT }}
      - name: Run all
        run:  make all
  docker-compose-cpdp-frr:
    name: Run docker-compose cpdp-frr CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./docker-compose/cpdp-frr
    if: needs.paths-filter.outputs.docker-compose-cpdp-frr == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.ENV_GITHUB_USER }}
          password: ${{ secrets.ENV_GITHUB_PAT }}
      - name: Run all
        run:  make all
  clab-cpdp-frr:
    name: Run containerlab cpdp-frr CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./clab/cpdp-frr
    if: needs.paths-filter.outputs.clab-cpdp-frr == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.ENV_GITHUB_USER }}
          password: ${{ secrets.ENV_GITHUB_PAT }}
      - name: Run all-clab
        run:  make all-clab
  clab-ixp-openbgpd:
    name: Run Clab ixp-openbgpd CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./clab/ixp-openbgpd
    if: needs.paths-filter.outputs.clab-ixp-openbgpd == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.ENV_GITHUB_USER }}
          password: ${{ secrets.ENV_GITHUB_PAT }}
      - name: Run all and clean
        run:  make all clean-all
  clab-rtbh:
    name: Run Clab RTBH CI
    runs-on: ubuntu-20.04
    needs: paths-filter
    defaults:
      run:
        working-directory: ./clab/rtbh
    if: needs.paths-filter.outputs.clab-rtbh == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Run all
        run:  make all
